# Generated by Django 2.2.20 on 2021-05-22 13:10

from django.db import migrations


def check_if_building_is_new(apps, schema_editor):
    new_building_year_marker = 2015
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= new_building_year_marker
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(check_if_building_is_new),
        ]
