# Generated by Django 2.2.20 on 2021-05-26 17:28
import phonenumbers

from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_number = flat.owners_phonenumber
        parsed_number = phonenumbers.parse(phone_number, 'RU')
        if phonenumbers.is_valid_number(parsed_number):
            pure_number = phonenumbers.format_number(parsed_number,
                phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.owner_pure_phone = pure_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
