# Generated by Django 2.2.20 on 2021-05-26 18:59

from django.db import migrations


def load_owners_names_and_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210526_2242'),
    ]

    operations = [
        migrations.RunPython(load_owners_names_and_phones),
    ]
