# Generated by Django 2.2.20 on 2021-05-27 06:40

from django.db import migrations


def connect_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        flat_owners = Owner.objects.filter(full_name=flat.owner)
        flat.flat_owners.set(flat_owners)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210526_2243'),
    ]

    operations = [
        migrations.RunPython(connect_owners_to_flats)
    ]